services:
  db:
    image: postgres:16
    container_name: example_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - examplestore_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  seq:
    image: datalust/seq:latest
    container_name: example_seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "${SEQ_PASSWORD:-seqadmin}"
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 15

  webapp:
    image: exampleuserdocer/example:latest
    container_name: example_webapp
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CONNECTION_STRING: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
      SERILOG__USING__0: Serilog.Sinks.Console
      SERILOG__USING__1: Serilog.Sinks.Seq
      SERILOG__MINIMUMLEVEL__DEFAULT: Information
      SERILOG__WRITETO__0__NAME: Console
      SERILOG__WRITETO__1__NAME: Seq
      SERILOG__WRITETO__1__ARGS__SERVERURL: "http://seq:80"
    volumes:
      - ./data-protection-keys:/home/exampleuser/.aspnet/DataProtection-Keys
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  examplestore_dbdata:
  seq_data:
